name: plot
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "10 5-7 * * *"
jobs:
  plot:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "plot_requirements.txt"
      - run: pip install -r plot_requirements.txt
      - run: python scripts/omicron_plot.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Plot update
          file_pattern: plots/omicron*
