name: transform
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"
jobs:
  transform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
      - run: bash scripts/pipeline.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data update
          file_pattern: data/meta_lineages.csv
  plot:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "requirements.txt"
      - run: pip install -r requirements.txt
      - run: python scripts/omicron_plot.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Plot update
          file_pattern: plots/omicron*
